set window._jsonp_callbacks only when invoked
this is to attempt to avoid the error:

    window._jsonp_callbacks = {}
    ^
    ReferenceError: window is not defined
    at Object.<anonymous> (/Users/patrick/src/tower/node_modules/dlite-jsonp/index.js:14:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/patrick/src/tower/dist/mason/script/pips/podcast.js:3:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)